server:
  port: 9009
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.35.233:3308/tutor?characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: tutor1qaz
  redis:
    host: 59.110.35.233  # Redis服务器地址
    port: 6379       # 端口（默认6379）
    password:        # 密码（没有则不填）
    database: 0      # 数据库索引（0-15）
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数
        max-idle: 8      # 最大空闲连接
        min-idle: 0      # 最小空闲连接
mybatis-plus:
#  typeAliasesPackage: com.yy.zingzone.mapper
  mapper-locations: classpath:/mapper/*Mapper.xml
  #  classpath*:com/strongdata/**/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: X-Token #JWT存储的请求头
  tokenHead: Bearer  #令牌前缀
  secret: junnan-oa-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间秒(60*60*24)
