server:
  port: 9009
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.32.28:3308/tutor?characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: tutor1qaz

mybatis-plus:
#  typeAliasesPackage: com.yy.zingzone.mapper
  mapper-locations: classpath:/mapper/*Mapper.xml
  #  classpath*:com/strongdata/**/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
