server:
  port: 9009
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.35.233:3308/tutor?characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: tutor1qaz

mybatis-plus:
#  typeAliasesPackage: com.yy.zingzone.mapper
  mapper-locations: classpath:/mapper/*Mapper.xml
  #  classpath*:com/strongdata/**/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: X-Token #JWT存储的请求头
  tokenHead: Bearer  #令牌前缀
  secret: junnan-oa-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间秒(60*60*24)
